### ISSUE TITLE
Database error

### ISSUE THREAD

**Issue by SPYmesu** [Gecolay/GHolo#2]
When trying to create hologram row
```
[14:53:40 INFO]: SPY_me issued server command: /gholo create justkiwi
[14:54:07 INFO]: SPY_me issued server command: /gholo addrow justkiwi &2&lJustKiwi
[14:54:07 WARN]: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'row_number, holo_id, content, o_x, o_y, o_z, l_yaw, l_pitch, data) VALUES (0, 'j' at line 1
[14:54:07 WARN]: 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:112)
[14:54:07 WARN]: 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:114)
[14:54:07 WARN]: 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:988)
[14:54:07 WARN]: 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1166)
[14:54:07 WARN]: 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1101)
[14:54:07 WARN]: 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1467)
[14:54:07 WARN]: 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1084)
[14:54:07 WARN]: 	at GHolo-1.0.1.jar//dev.geco.gholo.manager.DManager.execute(DManager.java:89)
[14:54:07 WARN]: 	at GHolo-1.0.1.jar//dev.geco.gholo.manager.HoloManager.createHoloRow(HoloManager.java:141)
[14:54:07 WARN]: 	at GHolo-1.0.1.jar//dev.geco.gholo.cmd.GHoloCommand.onCommand(GHoloCommand.java:227)
[14:54:07 WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[14:54:07 WARN]: 	at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:82)
[14:54:07 WARN]: 	at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73)
[14:54:07 WARN]: 	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31)
[14:54:07 WARN]: 	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19)
[14:54:07 WARN]: 	at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8)
[14:54:07 WARN]: 	at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5)
[14:54:07 WARN]: 	at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103)
[14:54:07 WARN]: 	at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:448)
[14:54:07 WARN]: 	at net.minecraft.commands.Commands.performCommand(Commands.java:355)
[14:54:07 WARN]: 	at net.minecraft.commands.Commands.performCommand(Commands.java:342)
[14:54:07 WARN]: 	at net.minecraft.commands.Commands.performCommand(Commands.java:337)
[14:54:07 WARN]: 	at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2241)
[14:54:07 WARN]: 	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$11(ServerGamePacketListenerImpl.java:2215)
[14:54:07 WARN]: 	at net.minecraft.server.TickTask.run(TickTask.java:18)
[14:54:07 WARN]: 	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:154)
[14:54:07 WARN]: 	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
[14:54:07 WARN]: 	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1578)
[14:54:07 WARN]: 	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:207)
[14:54:07 WARN]: 	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:128)
[14:54:07 WARN]: 	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1555)
[14:54:07 WARN]: 	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1548)
[14:54:07 WARN]: 	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:138)
[14:54:07 WARN]: 	at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1499)
[14:54:07 WARN]: 	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1509)
[14:54:07 WARN]: 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1345)
[14:54:07 WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:340)
[14:54:07 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by gecolay** [comment]
@SPYmesu Thank you for the report. The bug is now fixed with update 1.0.2.
